spring:
  application:
    name: employee-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/Desktop/young-fighter-course/company-services/employee-service/src/main/resources/data/company_employee;AUTO_SERVER=TRUE

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true